
#' @name mz_summary
#'
#' @aliases mz_summary
#'
#' @title Create a summary from adjacency list containing mass-differences with possible filter 
#'
#' @description
#' The function `mz_summary` creates a summary from the `AdjacencyMatrix`, containing mass-differences.
#' Individual mass differences are count over all features. The input may be 
#' `AdjacencyMatrix` originating from the function `structural`,
#' or `combine`. The parameter `filtered` will define if data will be 
#' filtered above a certain threshold or not. 
#' 
#' @param x
#' `AdjacencyMatrix`, a formal class of `AdjacencyMatrix` containing the mass-differences, that have previously 
#' been generated by the function `structural`or `combine`
#' 
#' @param filter
#' `number`/`FALSE`, leave empty or set to `FALSE` if unfiltered data are 
#' required. Select a `number` as a threshold where mz differences were filtered.
#' May be useful at visualization for big data. 
#' 
#' @details
#' Summarizes the adjacency matrices containing mass difference values, 
#' i.e. either adjacency list from `structural`or `combine` may be used.
#' Also the plots will be displayed. 
#' The default is filter = F, so the unfiltered summary will be returned. 
#' If filter is set to a `number`, e.g. 1000 only mz differences above 
#' this threshold will be displayed. 
#' The function can be applied for adjacency lists from `structural` and `combine`
#' 
#' @return 
#' `data.frame` containing the numbers of present mz differences and
#' corresponding name. Also a plot will be displayed.
#'
#' @author Liesa Salzer, \email{liesa.salzer@@helmholtz-muenchen.de}
#'
#' @examples
#' data("x_test", package = "MetNet")
#' transformation <- rbind(
#'     c("Monosaccharide (-H2O)", "C6H10O5", "162.0528234315"),
#'     c("Disaccharide (-H2O)", "C12H20O11", "340.1005614851"),
#'     c("Trisaccharide (-H2O)", "C18H30O15", "486.1584702945"))
#' transformation <- data.frame(group = transformation[, 1],
#'                                 formula = transformation[, 2],
#'                                 mass = as.numeric(transformation[, 3]))
#' am_struct <- structural(x_test, transformation, ppm = 5, directed = TRUE)
#' mz_summary(am_struct)
#'
#'
#'@export
#'
#'@import(dplyr)
mz_summary <- function(x, filter = F, ...){
  x_df <- as.data.frame(x)
  x_df <- x_df[x_df$binary == 1, ]

    sum_mass <- x_df %>% group_by(`mass_difference`) %>%  dplyr::summarise(count=n()) %>%
      as.data.frame()
    sum_transform <- x_df %>% group_by(`transformation`) %>% dplyr::summarise(count=n()) %>%
      as.data.frame()  %>% add_column(sum_mass$`mass_difference`)
    colnames(sum_transform) <- c("transformation", "counts", "mass_difference")
    sum_transform <- sum_transform %>% select(transformation, `mass_difference`, counts)
  
  
  if (filter == F) {
    plot_list <- ggplot(sum_transform, aes(x=transformation, y=counts)) + 
      geom_bar(stat = "identity") + 
      theme_minimal() + 
      coord_flip() + 
      labs(title = "Numbers of determined mass differences")
    
    plot(plot_list)
    
    return(sum_transform)
  }
  
  else if (filter != F) {
    sum_f <- filter(sum_transform,sum_transform$counts >= filter)
    plot_list_f <- ggplot(sum_f, aes(x=transformation, y=counts)) + 
      geom_bar(stat = "identity") + 
      theme_minimal() + 
      coord_flip() + 
      labs(title = "Numbers of determined mass differences", 
           subtitle = "(filtered)")
    
    plot(plot_list_f)
    
    return(sum_f)
    
  }
  
  
}
