#' @name mz_summary
#'
#' @aliases mz_summary
#'
#' @title Create a summary from adjacency list containing mass-differences
#'
#' @description
#' The function `mz_summary` creates a summary from the `AdjacencyMatrix`, 
#' containing mass-differences.Individual mass differences are count over 
#' all features. The input may be  `AdjacencyMatrix` originating from the 
#' function `structural`, or `combine`. The parameter `filtered` will define 
#' if data will be filtered above a certain threshold or not. 
#' 
#' @param x
#' `AdjacencyMatrix`, a formal class of `AdjacencyMatrix` containing the 
#' mass-differences, that have previously been generated by the function 
#' `structural`or `combine`
#' 
#' @param filter
#' `number`/`FALSE`, leave empty or set to `FALSE` if unfiltered data are 
#' required. Select a `number` as a threshold where mz differences were filtered.
#' May be useful at visualization for big data. 
#' 
#' @details
#' Summarizes the adjacency matrices containing mass difference values, 
#' i.e. either adjacency list from `structural`or `combine` may be used.
#' The default is filter = F, so the unfiltered summary will be returned. 
#' If filter is set to a `number`, e.g. 1000 only mz differences above 
#' this threshold will be displayed. 
#' The function can be applied for adjacency lists from `structural` and `combine`
#' 
#' @return 
#' `data.frame` containing the numbers of present mz differences and
#' corresponding name. 
#'
#' @author Liesa Salzer, \email{liesa.salzer@@helmholtz-muenchen.de}
#'
#' @examples
#' data("x_test", package = "MetNet")
#' transformation <- rbind(
#'     c("Monosaccharide (-H2O)", "C6H10O5", "162.0528234315"),
#'     c("Disaccharide (-H2O)", "C12H20O11", "340.1005614851"),
#'     c("Trisaccharide (-H2O)", "C18H30O15", "486.1584702945"))
#' transformation <- data.frame(group = transformation[, 1],
#'                                 formula = transformation[, 2],
#'                                 mass = as.numeric(transformation[, 3]))
#' am_struct <- structural(x_test, transformation, ppm = 5, directed = TRUE)
#' mz_summary(am_struct)
#'
#'
#'@export
#'
#'@importFrom dplyr %>%
mz_summary <- function(x, filter = FALSE, ...){
  
  if (!validObject(x)) 
    stop("'x' must be a valid 'AdjacencyMatrix' object")  
  
  x_df <- as.data.frame(x)
  
  if (!"combine" %in% type(x) & !"structural" %in% type(x) ) 
    stop("'x' does not contain a mass-difference adjacency matrix")
  
  if (!1 %in% x_df$binary) 
    stop("'x' does not contain any mass-differences")
  
  if (!is.numeric(filter) & !FALSE %in% filter) 
    stop("'filter' needs to be numeric or 'FALSE'")
  
  # if AdjacencyMatrix from `combine` is used 
  if("combine" %in% type(x)){
    x_df <- x_df[x_df$combine_binary == 1, ]
    x_df <- na.omit(x_df, "combine_binary")
    
    sum_mass <- x_df %>% 
      dplyr::group_by(combine_mass_difference) %>%  
      dplyr::summarise(count = dplyr::n()) %>%
      as.data.frame()
    
    sum_transform <- x_df %>% 
      dplyr::group_by(combine_transformation) %>% 
      dplyr::summarise(count = dplyr::n()) %>%
      as.data.frame()  %>% 
      tibble::add_column(sum_mass$combine_mass_difference)
  }
  
  # if AdjacencyMatrix from `structural` is used 
  else {
    x_df <- x_df[x_df$binary == 1, ]
    
    sum_mass <- x_df %>% 
      dplyr::group_by(mass_difference) %>%  
      dplyr::summarise(count = dplyr::n()) %>%
      as.data.frame()
    
    sum_transform <- x_df %>% 
      dplyr::group_by(transformation) %>% 
      dplyr::summarise(count = dplyr::n()) %>%
      as.data.frame()  %>% 
      tibble::add_column(sum_mass$mass_difference)
  }
  
  colnames(sum_transform) <- c("transformation", "counts", "mass_difference")
  sum_transform <- sum_transform %>% 
    dplyr::select(transformation, mass_difference, counts)
  
  if (filter == FALSE | filter <= 1) {
    return(sum_transform)
  }
  
  else {
    sum_f <- filter(sum_transform,sum_transform$counts >= filter)
    return(sum_f)
    
  }
  
  
}




#' @name mz_vis
#'
#' @aliases mz_vis
#'
#' @title Visualize mass-difference distribution 
#'
#' @description
#' The function `mz_vis` visualizes the mass-difference distribution,
#' which has been summarized by `mz_summary`. 
#' 
#' @param x
#' `list`, previously generated by `mz_summary`. Needs to contain
#' the columns "transformation", "mass_difference" and "counts".
#' 
#' 
#' @details
#' Plots the mass-difference distribution, summarized
#' by `mz_summary`. 
#' Visualization is performed using ggplot2
#' 
#' @return 
#' `ggplot` object and corresponding barplot for visualizations
#'
#' @author Liesa Salzer, \email{liesa.salzer@@helmholtz-muenchen.de}
#'
#' @examples
#' data("x_test", package = "MetNet")
#' transformation <- rbind(
#'     c("Monosaccharide (-H2O)", "C6H10O5", "162.0528234315"),
#'     c("Disaccharide (-H2O)", "C12H20O11", "340.1005614851"),
#'     c("Trisaccharide (-H2O)", "C18H30O15", "486.1584702945"))
#' transformation <- data.frame(group = transformation[, 1],
#'                                 formula = transformation[, 2],
#'                                 mass = as.numeric(transformation[, 3]))
#' am_struct <- structural(x_test, transformation, ppm = 5, directed = TRUE)
#' mz_sum <- mz_summary(am_struct)
#' mz_vis(mz_sum)
#'
#'@export
mz_vis <- function(x, ...){
   
  if (!all(c("transformation", "mass_difference", "counts") %in% colnames(x))) 
    stop("'x' has not the right columns 'transformation', 'mass_difference', 'counts'")  
  
    plot_list <- ggplot2::ggplot(x, 
                                 ggplot2::aes_string(x="transformation", y="counts")) + 
      ggplot2::geom_bar(stat = "identity") + 
      ggplot2::theme_minimal() + 
      ggplot2::coord_flip() + 
      ggplot2::labs(title = "Numbers of determined mass differences")
    
    plot(plot_list)
  
  
}




